options:
    dfs_blocksize:
        type: int
        default: 134217728
        description: |
            The default block size for new files (default to 64MB). Increase
            this in larger deployments for better large data set performance.
    dfs_replication:
        type: int
        default: 3
        description: |
            Default block replication. The actual number of replications can be
            specified when the file is created. The default is used if
            replication is not specified at file creation time.
    journalnode_quorum_size:
        type: int
        default: 3
        description: |
             Minimum number of journalnodes that must be ready before the shared
             edits dir will be initialized (aka formatted) on each journalnode.
